export const GET_BANKS = 'GET_BANKS';
export const GET_BANKS_SUCCESS = 'GET_BANKS_SUCCESS';

export const ADD_BANK = 'ADD_BANK';
export const ADD_BANK_SUCCESS = 'ADD_BANK_SUCCESS';

export const UPDATE_ACTIVE_BANK = 'UPDATE_ACTIVE_BANK';
